### ISSUE TITLE
VPG checklist

### ISSUE THREAD

**Issue by leot10** [leot10/VPG#1]
# VirtualPets

- [ ] Create a `Pet` or `Animal` Class
  - [ ] Define `Name`, `Hunger`, and `Boredom` properties
  - [ ] Define a constructor method that appropriately sets the mentioned properties
  - [ ] Look into how to construct `get; set;` properties for this task (https://stackoverflow.com/questions/5096926/what-is-the-get-set-syntax-in-c)
  - [ ] Create appropriate methods, including (but not limited to):
    - [ ] Talk
      - [ ] Let the pet identify itself (`"Hi, I'm {name}!"`)
      - [ ] Say something about its mood based on hunger + boredom
    - [ ] Eat
      - [ ] Include a parameter that reduces the Hunger level by the value of the argument
      - [ ] Do not let the Hunger level go below 0
    - [ ] Play
      - [ ] Include a parameter that reduces the Boredom level by the value of the argument
      - [ ] Do not let the Boredom level go below 0

*The virtual pet class should also include a method that corresponds to time passing and which should also increase the hunger and boredom levels by a set amount, say 4 units.*

**The class should be used in a game with the following structure:**
```js
//  Create and initialise two virtual pets
    while (playGame)
    {
        // display a menu asking the pet keeper to enter a number to
        // get the pet to either eat, talk or play the game

        // eating or playing with the pet will reduce its hunger or
        // boredom level by a random number within a given range (but not going below zero)

        // if the (boredom level + hunger level) goes above a certain
        // level the pet will, sadly, expire

        // increase time by a set amount.
    }
// announce surviving pet
```

+ The C# code should follow the good practice guidelines mentioned during lectures and labs.
+ There are additional improvements that can be made, for example dealing with bad input.

**In marking the following will be taken into account:**
- [ ] welcome, messages to console and input/output
- [ ] construction of class with appropriate variables, methods and access modifiers
- [ ] creation and initialisation of virtual pets
- [ ] functioning menu
- [ ] working game loop
- [ ] test of â€œmoodâ€ each in loop and action taken
- [ ] implementation of time
- [ ] good practice
- [ ] extras or other features
